###
GET http://localhost:3001/api/blogs/

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inl5bGlhbmcyMTEiLCJpZCI6IjY2MjU3ZjQ3YjU1ZjU5YTUzNzViNDllYiIsImlhdCI6MTcxMzc1MDg4NCwiZXhwIjoxNzEzNzU0NDg0fQ.EhcO0fa9jt7W_508tMjyHCxNyH9E--gJ0rqQfecl44A

{
    "title": "second post",
    "author": "yyliang",
    "url": "https://fakeurl.com",
    "likes": 1

}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NjI1YzdiMzNmYTIyNThlNDI1OGY0YjYiLCJpYXQiOjE3MTM3NTIwNTQsImV4cCI6MTcxMzc1NTY1NH0.5O-c77C8OhcgTnDLUHPanH-hy9EaenqJPb6Ygom0mRA

{
    "title": "test",
    "author": "admin",
    "url": "https://fakeurl.com",
    "likes": 1
}

###
PUT http://localhost:3001/api/blogs/661c79e6f1a3f98e434cb326 HTTP/1.1
content-type: application/json

{
    "title": "updated post",
    "author": "me again",
    "likes": 2
}

###
DELETE http://localhost:3001/api/blogs/6625c8463fa2258e4258f4c5
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NjI1YzdiMzNmYTIyNThlNDI1OGY0YjYiLCJpYXQiOjE3MTM3NTIxMTYsImV4cCI6MTcxMzc1NTcxNn0.saRnnJ4Cw7SY2d37rwO3V4LEnS_kt-G02zpRPVnOk-0
