GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "testing note",
    "userId": "662566aea82ec6816bb01a55"
}

###
DELETE http://localhost:3001/api/notes/660e02bf0b17c20836c032bb

###
PUT http://localhost:3001/api/notes/660e02a60b17c20836c032b7
content-type: application/json

{
    "content": "repalace",
    "important": "false"
}
