### Create User
POST http://localhost:3001/api/users
content-type: application/json

{
    "name": "mluukkai",
    "username": "mluukkai",
    "password": "salainen"

}

### Get Users
GET http://localhost:3001/api/users
